name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  sync-tag:
    name: Sync Tag with Package version
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-22.04
    outputs:
      isReleaseNew: ${{ steps.bump_tag.outputs.isNew }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x # Run with latest stable Deno.

      - name: Bump Tag
        id: bump_tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
        run: |
          deno task bump-tag &&\
            echo "isNew=true" >> "$GITHUB_OUTPUT" ||\
            echo "isNew=false" >> $GITHUB_OUTPUT

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    needs: sync-tag
    if: needs.sync-tag.outputs.isReleaseNew == 'true'
    outputs:
      changelog: ${{ steps.github_release.outputs.changelog }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build Changelog
        id: github_release
        run: echo "changelog=$(npx conventional-changelog-cli --preset conventionalcommits)" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{ needs.changelog.outputs.changelog }}
