name: 'Release'

on: push

jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "# | TEST 1"
  test2:
    name: Test 2
    # if: startsWith(github.ref, 'refs/tags/')
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "# | TEST 2"
  ghRef:
    name: Github REF
    runs-on: ubuntu-latest
    steps:
      - name: Shows current ref
        run: echo ${{ github.ref }}
  changelog:
    name: Changelog
    # if: startsWith(github.ref, 'refs/tags/')
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.github_release.outputs.changelog }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build Changelog
        id: github_release
        run: echo "changelog=$(npx conventional-changelog-cli --preset conventionalcommits)" >> $GITHUB_OUTPUT
  release:
    name: Release
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{ needs.changelog.outputs.changelog }}
