name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  test1:
    name: Test 1 (expect run every time)
    runs-on: ubuntu-latest
    steps:
      - name: Shows run message
        run: echo "TEST1 RUN"
  test2:
    name: Test 2 (expect run only on specific commits)
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: Shows run message
        run: echo "TEST2 RUN"

  # sync-tag:
  #   name: Sync Tag with Package version
  #   if: startsWith(github.event.head_commit.message)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "test"
  # changelog:
  #   name: Changelog
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   outputs:
  #     changelog: ${{ steps.github_release.outputs.changelog }}
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.x
  #     - name: Build Changelog
  #       id: github_release
  #       run: echo "changelog=$(npx conventional-changelog-cli --preset conventionalcommits)" >> $GITHUB_OUTPUT
  # release:
  #   name: Release
  #   needs: changelog
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Create Release
  #       uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
  #       with:
  #         body: ${{ needs.changelog.outputs.changelog }}
