name: Sync Tag

on:
  push:
    branches:
      - main

jobs:
  sync-tag:
    name: Sync Tag
    runs-on: ubuntu-22.04
    steps:
      - name: Setup GIT
        run: |
          git config --global user.name "Mateus Felipe Gonçalves"
          git config --global user.email "mateusfelipefg77@gmail.com"

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x # Run with latest stable Deno.

      - name: Bump Tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
        run: |
          deno task bump-tag
